# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-12 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(default='PROCESSING', max_length=20),
        ),
    ]
