# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-09 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='ref_code',
            field=models.CharField(default='NQ2L0SGME5', editable=False, max_length=10, unique=True),
        ),
    ]
