# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-09 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_auto_20181109_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='ref_code',
            field=models.CharField(default='UZPK7I20XV', editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
