# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-04-02 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='number',
            old_name='digits',
            new_name='phone',
        ),
    ]
